# @package _global_

runtime:
  default_scenario_parameters:
    cameras:
    -
      height: 320
      width: 512
      logical_id: camera_front_wide_120fov

      frame_interval_us: 33_000
      shutter_duration_us: 15_000
      first_frame_offset_us: -15_000
    -
      height: 320
      width: 512
      logical_id: camera_front_tele_30fov

      frame_interval_us: 33_000
      shutter_duration_us: 15_000
      first_frame_offset_us: -15_000
