# @package _global_

runtime:
  default_scenario_parameters:
      cameras:
      -
        height: 320
        width: 512
        logical_id: camera_front_wide_120fov

        # If you change this see note in base_config.yaml about `driver.inference.Cframes_subsample`
        frame_interval_us: 100_000
        shutter_duration_us: 30_000
        first_frame_offset_us: -30_000
