[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alpasim_utils"
version = "0.52.0"
description = "Utility functions for Alpamayo Sim"
requires-python = ">=3.11,<=3.12"
dependencies = [
  "alpasim_grpc",
  "dataclasses-json>=0.6.7",
  "numpy",
  "scipy",
  "aiofiles",
  "csaps",
  "imageio[ffmpeg]",
  "pandas",
  "pytest",
  "pytest-asyncio",
  "trajdata-alpasim @ git+https://github.com/NVlabs/trajdata.git@alpasim"
]

[project.scripts]
asl-to-frames = "alpasim_utils.asl_to_frames.__main__:main"
print-asl = "alpasim_utils.print_asl.__main__:main"

[[project.authors]]
name = "Michal Tyszkiewicz"
email = "mtyszkiewicz@nvidia.com"

[tool.uv.sources]
alpasim_grpc = {workspace = true}

[tool.setuptools.packages.find]
where = ["."]
include = ["alpasim_utils*"]
