# @package _global_
# Config for running on workstations with a single 40gb+ GPU, see TUTORIAL
# for extra instructions. In short, use cmd line arg "+deploy=local" with wizard.

defaults:
  - _self_
  - /stable_manifest/oss

defines:
  # The repo-relative resolver makes the path relative to the git repo root.
  filesystem: ${repo-relative:"data"}

services:
  driver:
    replicas: 1
    gpus: [0]

  sensorsim:
    replicas: 1
    gpus: [0]

  physics:
    replicas: 1
    gpus: [0]

  controller:
    replicas: 1
    gpus: null
