# Should be used in defaults list, e.g.
# - /driver: alpamayo

write_debug_images: false
# Trajectory recovery heuristic parameters; set `enabled` true to activate
# Note: remember to set `send_recording_ground_truth` to true as well.
trajectory_recovery:
  enabled: false
  num_points_comparison: 20
  num_points_recovery: 40
  max_distance_threshold: 3.0
inference:
  # Overwrite the minimum required historical timesteps that was temporarily increased
  # as a WAR for failing replay tests.
  min_num_historical_waypoints: \${inference.num_historical_waypoints}
  # Overwrite the rig file to match default alpasim rig config.
  # TODO: Remove this once Alpasim is updated with the new rig config.
  viz_cfg:
    rig_calibration_file: "3415_rig.json"
  selection_strategy: CLOSEST_3D
