# @package _global_

# Explicitly sets the vehicle dimensions for the simulator.
# Even if you want to modify just a single dimension, with the default being `vehicle: null`,
# you need to specify all other dimensions as well. This config file simplifies that by allowing
# `+vehicle=custom runtime.default_scenario_parameters.vehicle.aabb_x_m=<your value>`.
runtime:
  default_scenario_parameters:
    vehicle:
      aabb_x_m: 5.393
      aabb_y_m: 2.109
      aabb_z_m: 1.503
      aabb_x_offset_m: -1.3
      aabb_y_offset_m: 0.0
      aabb_z_offset_m: 0.0
